/**
 * Published delivery-area settlement lists, one per storefront.
 *
 * Separated from `catalog.ts` purely for size: these are transcriptions of the
 * lists the retailers print on their own delivery pages, and inlining ~700 names
 * would bury the terms they belong to.
 *
 * WHY A LIST AND NOT `national`
 *
 * Every one of these storefronts was recorded as covering the whole country,
 * which is what an unfilled coverage row looks like. It is also the single most
 * expensive thing to get wrong here: `national` answers "yes, they deliver to
 * you" for every address in Israel, so a shopper in Eilat was being offered a
 * storefront that stops at Netanya. Rami Levy carried `national` at confidence
 * `verified`, and publishes a 270-settlement list.
 *
 * Names are stored exactly as the retailer writes them. Matching runs through
 * `canonicalizeCity`, whose alias table already collapses "תל אביב-יפו" and
 * "תל אביב" onto one key, so the retailer's spelling does not have to be
 * normalised here.
 *
 * WHAT IS DELIBERATELY MISSING
 *
 * Several lists also carry region phrases: "ישובי עמק חפר", "מושבי אופקים",
 * "קרית מלאכי והסביבה". They are dropped rather than stored, because a rule that
 * can never match is worse than an absent one: it reads as coverage in the table
 * and behaves as none. The cost is a false "not served" for a shopper in one of
 * those villages, which is the safe direction to be wrong about a delivery
 * promise. Each list notes how many phrases were dropped.
 */
import { normalizeCityKey } from "@super-mcp/shared";


/** רמי לוי שיווק השקמה (רמי לוי אונליין): 270 settlements, read 2026-08-02 from https://www.rami-levy.co.il/he/orders-and-deliveries. */
export const RAMI_LEVY_SETTLEMENTS: readonly string[] = [
  "מעלה אדומים",
  "מודיעין",
  "רעננה",
  "אשקלון",
  "קריית שמונה",
  "כרמיאל",
  "מבשרת ציון",
  "פסגת זאב",
  "נווה יעקב",
  "גבעה הצרפתית",
  "גבעת המבתר",
  "רמת אשכול",
  "שמואל הנביא",
  "טלזסטון",
  "קריית יערים",
  "אדם",
  "ענתות",
  "הר הדר",
  "בית נקופה",
  "רמות",
  "מעלה מכמש",
  "מצפה דני",
  "כפר אדומים",
  "קליה",
  "אלמוג",
  "בית הערבה",
  "מצפה יריחו",
  "ורד יריחו",
  "אלון",
  "קדר",
  "מבוא חורון",
  "שוהם",
  "חשמונאים",
  "מתתיהו",
  "ברכפלד",
  "קריית ספר",
  "מודיעין עלית",
  "רחובות",
  "נס ציונה",
  "כפר האורנים",
  "כפר טרומן",
  "בית נחמיה",
  "בת עוזיאל",
  "פדיה",
  "פתחיה",
  "בית חשמונאי",
  "עזריה",
  "מרכז וצפון תל אביב (עד ארלוזורוב)",
  "פתח תקווה",
  "ראש העין",
  "גבעתיים",
  "רמת גן",
  "חולון",
  "רמת אפעל",
  "אזור",
  "גבעת שמואל",
  "גני תקווה",
  "קריית אונו",
  "סביון",
  "נחלים",
  "כפר סירקין",
  "בת ים",
  "הרצליה",
  "רמת השרון",
  "הוד השרון",
  "כפר סבא",
  "כוכב יאיר",
  "צור יצחק",
  "צור יגאל",
  "גליל ים",
  "הכפר הירוק",
  "אלישמע",
  "רמות השבים",
  "נוה ירק",
  "גני עם",
  "בני ציון",
  "חרוצים",
  "בצרה",
  "אבן יהודה",
  "כפר נטר",
  "בית יהושע",
  "תל יצחק",
  "ניצן",
  "באר גנים",
  "מבקיעים",
  "זיקים",
  "בית שקמה",
  "בת הדר",
  "יד מרדכי",
  "שדרות",
  "גיאה",
  "גברעם",
  "תלמי יפה",
  "יד נתן",
  "כפר סילבר",
  "ברכיה",
  "כרמיה",
  "ניר ישראל",
  "ניצנים",
  "כוכב מיכאל",
  "אלקנה",
  "שערי תקווה",
  "אורנית",
  "עץ אפרים",
  "אשדוד",
  "גן יבנה",
  "יד בנימין",
  "שתולים",
  "כפר אביב",
  "גבעת וושינגטון",
  "גני טל",
  "ניר גלים",
  "חפץ חיים",
  "בית חלקיה",
  "חדרה",
  "גבעת אולגה",
  "קיסריה",
  "אור עקיבא",
  "פרדס חנה כרכור",
  "בת חפר",
  "מצפה אילן",
  "חריש",
  "תל מנשה",
  "שקד",
  "חיננית",
  "קציר",
  "ריחן",
  "זכרון יעקב",
  "בנימינה",
  "גבעת עדה",
  "כפר יונה",
  "תל מונד",
  "חרות",
  "בני דרור",
  "עין ורד",
  "נתניה",
  "חיפה והקריות",
  "עכו",
  "נשר",
  "נהריה",
  "סער",
  "מצפה עדי",
  "יסעור",
  "הגושרים",
  "מעיין ברוך",
  "יובל-דפנה",
  "שאר יישוב",
  "דן",
  "שניר",
  "מטולה",
  "כפר גלעדי",
  "משגב עם",
  "כפר בלום",
  "שדה נחמיה",
  "עמיר",
  "נאות מרדכי",
  "בית הלל",
  "מרגליות",
  "מנרה",
  "יפתח",
  "מלכיה",
  "רמות נפתלי",
  "דישון",
  "אביבים",
  "ראש פינה",
  "יסוד המעלה",
  "איילת השחר",
  "מחניים",
  "חצור הגלילת",
  "שדה אליעזר",
  "ביה\"ס שדה חרמון",
  "חורשת טל",
  "רשות החולה",
  "שמורת תל-דן",
  "אליפלט",
  "משמר הירדן",
  "להבות הבשן",
  "גונן",
  "ברוכים",
  "קלע אלון",
  "שמיר",
  "מרום גולן",
  "עין זיוון",
  "אורטל",
  "קדמת צבי",
  "קצרין",
  "אלוני בשן",
  "קשת",
  "גילון",
  "גן תעשיה- לבון",
  "חלוץ",
  "כישור",
  "כמון",
  "לבון",
  "לפידות",
  "מכמנים",
  "פלך",
  "צורית",
  "תובל",
  "אבטליון",
  "לוטם",
  "צביה",
  "שורשים",
  "כפר ורדים",
  "מעלות תרשיחא",
  "אשבל",
  "אשחר",
  "יובלים",
  "יודפת",
  "יעד",
  "מנוף",
  "משגב",
  "עצמון",
  "שגב",
  "קורנית",
  "רקפת",
  "שכניה",
  "אור הגנוז",
  "אמירים",
  "בר יוחאי",
  "כפר שמאי",
  "מרון",
  "ספסופה",
  "פרוד",
  "שפר",
  "מורשת",
  "מצפה אביב",
  "דמיידה",
  "אפיק",
  "בני יהודה",
  "גבעת יואב",
  "כפר חרוב",
  "נאות גולן",
  "נטור",
  "מבוא חמה",
  "מיצר",
  "אבני איתן",
  "אלי-עד",
  "גשור",
  "חספין",
  "נוב",
  "רמת מגשימים",
  "ירושלים",
  "תל אביב - יפו",
  "באר שבע",
  "ראשון לציון",
  "בית שמש",
  "קריית גת",
  "ירוחם",
  "אופקים",
  "נתיבות",
  "יבנה",
  "קריית מלאכי",
  "גדרה",
  "לוד",
  "רמלה",
  "ביתר עילית",
  "אלעד",
  "בני ברק",
  "אור יהודה",
  "טבריה",
  "יקנעם עילית",
  "טירת כרמל",
  "קריית ביאליק",
  "אפרת",
  "דימונה",
  "עפולה",
  "אריאל",
  "חיפה",
  "מודיעין עילית",
];

/** קרפור אונליין (Carrefour Online): 55 settlements, read 2026-08-02 from https://www.carrefour.co.il/retailer/times. Dropped 20 region phrase(s) naming no single settlement. */
export const CARREFOUR_SETTLEMENTS: readonly string[] = [
  "חולון , בת ים",
  "אזור",
  "ראשון לציון מערב",
  "גני תקווה וקרית אונו",
  "אור יהודה , יהוד , סביון",
  "אור עקיבא",
  "זכרון יעקב",
  "חדרה",
  "חריש",
  "פרדס חנה",
  "בנימינה",
  "נתניה",
  "אילת",
  "אשקלון",
  "נתיבות אופקים",
  "שדרות",
  "אשדוד",
  "באר שבע",
  "עומר",
  "בית שמש",
  "צור הדסה",
  "רמת גן גבעתיים",
  "בני ברק",
  "בני ברק עסקי",
  "תל אביב",
  "תל אביב דרום/יפו",
  "ק.אתא ביאליק",
  "ק.מוצקין ים חיים",
  "חיפה עיר תחתית",
  "טירת הכרמל",
  "חיפה",
  "עכו , נהריה",
  "רמת השרון, רמת אביב",
  "מערב ירושלים",
  "צפון ירושלים",
  "מזרח ירושלים",
  "מבשרת ציון",
  "הוד השרון",
  "כוכב יאיר אלישמע",
  "כפר סבא",
  "רעננה",
  "הרצליה",
  "צור יצחק",
  "אורנית שערי תקווה אלקנה",
  "פתח תקווה",
  "ראש העין",
  "עפולה",
  "דבורה, חבר, רם און, אדירים",
  "רמלה לוד",
  "מודיעין מכבים רעות",
  "רחובות",
  "יבנה",
  "ק.עקרון",
  "גדרה",
  "שוהם",
];

/** קוויק (Quik): 49 settlements, read 2026-08-02 from https://www.quik.co.il/retailer/times. Dropped 10 region phrase(s) naming no single settlement. */
export const QUIK_SETTLEMENTS: readonly string[] = [
  "חולון , בת ים",
  "אזור",
  "ראשון לציון מערב",
  "גני תקווה וקרית אונו",
  "אור יהודה , יהוד , סביון",
  "אור עקיבא",
  "זכרון יעקב",
  "חדרה",
  "חריש",
  "פרדס חנה",
  "בנימינה",
  "נתניה",
  "אילת",
  "אשקלון",
  "נתיבות אופקים",
  "שדרות",
  "אשדוד",
  "רמת גן גבעתיים",
  "בני ברק",
  "בני ברק עסקי",
  "תל אביב",
  "תל אביב דרום/יפו",
  "ק.אתא ביאליק",
  "ק.מוצקין ים חיים",
  "חיפה עיר תחתית",
  "טירת הכרמל",
  "חיפה",
  "עכו , נהריה",
  "רמת השרון, רמת אביב",
  "מערב ירושלים",
  "צפון ירושלים",
  "מזרח ירושלים",
  "מבשרת ציון",
  "הוד השרון",
  "כוכב יאיר אלישמע",
  "כפר סבא",
  "רעננה",
  "הרצליה",
  "צור יצחק",
  "אורנית שערי תקווה אלקנה",
  "פתח תקווה",
  "ראש העין",
  "רמלה לוד",
  "מודיעין מכבים רעות",
  "רחובות",
  "יבנה",
  "ק.עקרון",
  "גדרה",
  "שוהם",
];

/** ביתן Online (יינות ביתן): 51 settlements, read 2026-08-02 from https://www.ybitan.co.il/retailer/times. Dropped 10 region phrase(s) naming no single settlement. */
export const YEINOT_BITAN_SETTLEMENTS: readonly string[] = [
  "חולון , בת ים",
  "אזור",
  "ראשון לציון מערב",
  "גני תקווה וקרית אונו",
  "אור יהודה , יהוד , סביון",
  "אור עקיבא",
  "זכרון יעקב",
  "חדרה",
  "חריש",
  "פרדס חנה",
  "בנימינה",
  "נתניה",
  "אילת",
  "אשקלון",
  "נתיבות אופקים",
  "שדרות",
  "אשדוד",
  "בית שמש",
  "צור הדסה",
  "בני ברק",
  "רמת גן גבעתיים",
  "בני ברק עסקי",
  "תל אביב",
  "תל אביב דרום/יפו",
  "ק.אתא ביאליק",
  "ק.מוצקין ים חיים",
  "חיפה עיר תחתית",
  "טירת הכרמל",
  "חיפה",
  "עכו , נהריה",
  "רמת השרון, רמת אביב",
  "מערב ירושלים",
  "צפון ירושלים",
  "מזרח ירושלים",
  "מבשרת ציון",
  "אורנית שערי תקווה אלקנה",
  "פתח תקווה",
  "ראש העין",
  "הוד השרון",
  "כוכב יאיר אלישמע",
  "כפר סבא",
  "רעננה",
  "הרצליה",
  "צור יצחק",
  "יבנה",
  "מודיעין מכבים רעות",
  "גדרה",
  "רמלה לוד",
  "רחובות",
  "ק.עקרון",
  "שוהם",
];

/** ויקטורי: 50 settlements, read 2026-08-02 from https://www.victoryonline.co.il/v2/retailers/1470/areas?appId=4&languageId=2&deliveryTypeId=1. Dropped 18 region phrase(s) naming no single settlement. */
export const VICTORY_SETTLEMENTS: readonly string[] = [
  "אשקלון",
  "כפר סילבר",
  "ראשון לציון",
  "חדרה",
  "גבעת אולגה",
  "חריש",
  "נתניה",
  "בני עי\"ש",
  "גן יבנה וסביבה",
  "שתולים, עזריקם, שדה עוזיהו, אמונים, גבעתי, עזר ,בית עזרא, ניצן, באר גנים",
  "רמת גן 1",
  "גבעתיים",
  "מודיעין מכבים רעות",
  "באר יעקב",
  "תל אביב צפון",
  "כפר האורנים,לפיד,שילת,כפר רות, נוף איילון",
  "תל אביב יפו מרכז דרום",
  "חולון, בת ים, בית דגן, אזור",
  "בני ברק",
  "בית שמש",
  "באר שבע, עומר",
  "להבים,אשל הנשיא,משמר הנגב,שובל,גבעות בר,תפרח",
  "עוטף",
  "עלה נגב, עדי נגב",
  "ברוש, תאשור, תדהר",
  "עוטף עזה",
  "הרצליה",
  "רמת השרון",
  "רעננה",
  "כפר סבא,הוד השרון",
  "אלקנה,אורנית,שערי תקוה,עץ אפרים",
  "יהוד, אור יהודה",
  "בקעת אונו",
  "עפולה, מרחביה",
  "חבל התענכים",
  "רחובות",
  "מזכרת בתיה, בית אלעזרי, כפר ביל\"ו, קרית עקרון, גבעת ברנר",
  "צפון ירושלים",
  "ירושלים 2",
  "ירושלים צפון חדש",
  "ירושלים צפון קצה למעלה",
  "שדרות הסביבה ועוטף",
  "קרית גת, אבן שמואל",
  "אשדוד",
  "ניר גלים,בני דרום,גן הדרום,נווה הרצוג",
  "טירת הכרמל",
  "חיפה, נשר",
  "עתלית",
  "החותרים",
  "אקים דימונה",
];

/** מחסני השוק: 69 settlements, read 2026-08-02 from https://www.mck.co.il/v2/retailers/1107/branches/836/areas?appId=4&deliveryTypeId=1&deliveryTypeId=5&languageId=2. Dropped 1 region phrase(s) naming no single settlement. */
export const MACHSANEI_SETTLEMENTS: readonly string[] = [
  "באר שבע",
  "דימונה",
  "אופקים",
  "להבים",
  "בית קמה",
  "דבירה",
  "שובל",
  "להב",
  "אשכולות",
  "גבעות בר",
  "רהט",
  "מיתר",
  "עומר",
  "כרמית",
  "סנסנה",
  "נגוהות",
  "טנא עומרים",
  "דרום הר חברון",
  "סוסיה",
  "מעון",
  "ערד",
  "קריית גת",
  "שחר",
  "ניר ח\"ן",
  "נהורה",
  "נוגה",
  "עוצם",
  "שדה דוד",
  "ורדון",
  "ניר בנים",
  "זרחיה",
  "זבדיאל",
  "קוממיות",
  "אלומה",
  "יד נתן",
  "רווחה",
  "עוזה",
  "נועם",
  "אבן שמואל",
  "איתן",
  "שלווה",
  "אחוזם",
  "לכיש",
  "נטע",
  "שומריה",
  "חיפה",
  "נשר",
  "יקנעם",
  "קריית טבעון",
  "שער העמקים",
  "קרית אתא",
  "קרית ביאליק",
  "כפר ביאליק",
  "קרית מוצקין",
  "קרית ים",
  "קרית חיים",
  "נוף הגליל",
  "נצרת",
  "עין יהב",
  "עידן",
  "ספיר",
  "צוקים",
  "צופר",
  "נאות הכיכר",
  "עין תמר",
  "נווה זוהר",
  "חצבה",
  "פארן",
  "מצפה רמון",
];

/** סופר יודה: 5 settlements, read 2026-08-02 from https://www.yuda.co.il/v2/retailers/1492/branches/2499/areas. */
export const SUPER_YUDA_SETTLEMENTS: readonly string[] = [
  "תל אביב",
  "רמת השרון",
  "חולון",
  "ראשון לציון (מערב)",
  "צור יצחק",
];

/** פוליצר: 11 settlements, read 2026-08-02 from https://www.politzer-c.co.il/. Dropped 3 region phrase(s) naming no single settlement. */
export const POLITZER_SETTLEMENTS: readonly string[] = [
  "קיסריה",
  "שדות ים",
  "נאות גולף",
  "אור עקיבא",
  "אור ים",
  "חדרה",
  "חוגלה",
  "חיבת ציון",
  "אליכין",
  "חרב לאת",
  "פארק התעשייה קיסריה",
];

/** טיב טעם: 23 settlements, read 2026-08-02 from https://www.tivtaam.co.il/v2/retailers/1062/branches/924/areas?appId=4&deliveryTypeId=1&languageId=1. */
export const TIV_TAAM_RAMAT_HAHAYAL: readonly string[] = [
  "רמת השרון",
  "רמת גן",
  "גבעתיים",
  "בני ברק",
  "תל אביב - רמת אביב",
  "תל אביב - רמת החייל",
  "תל אביב - אפקה",
  "הרצליה",
  "ראש העין",
  "כפר סירקין",
  "אורנית",
  "גבעת השלושה",
  "עינת",
  "כוכב יאיר",
  "אייל",
  "חגור",
  "חורשים",
  "צופים",
  "ירחיב",
  "נווה ירק",
  "צור יצחק",
  "מתן",
  "צור יגאל",
];

/** טיב טעם: 23 settlements, read 2026-08-02 from https://www.tivtaam.co.il/v2/retailers/1062/branches/3463/areas?appId=4&deliveryTypeId=1&languageId=1. */
export const TIV_TAAM_RISHON: readonly string[] = [
  "ראשון לציון",
  "חולון",
  "בת ים",
  "אזור",
  "תל אביב - מרכז",
  "תל אביב - דרום",
  "פתח תקווה",
  "בקעת אונו",
  "רמלה",
  "לוד",
  "מודיעין מכבים רעות",
  "כפר האורנים",
  "כרמי יוסף",
  "שוהם",
  "כפר טרומן",
  "בית נחמיה",
  "חדיד",
  "בית עריף",
  "גבעת כח",
  "טירת יהודה",
  "ברקת",
  "פארק תעשייה חבל מודיעין",
  "ירושלים",
];

/** טיב טעם: 78 settlements, read 2026-08-02 from https://www.tivtaam.co.il/v2/retailers/1062/branches/943/areas?appId=4&deliveryTypeId=1&languageId=1. Dropped 1 region phrase(s) naming no single settlement. */
export const TIV_TAAM_NETANYA: readonly string[] = [
  "נתניה",
  "כפר יונה",
  "גאולים",
  "בית יצחק",
  "הדר עם",
  "ינוב",
  "גנות הדר",
  "כפר חיים",
  "נורדיה",
  "תנובות",
  "משמר השרון",
  "כפר ידידיה",
  "חניאל",
  "כפר מונש",
  "מעברות",
  "העוגן",
  "שער חפר",
  "תל מונד",
  "קדימה",
  "כפר הס",
  "בני דרור",
  "עין ורד",
  "עזריאל",
  "עין שריד",
  "פורת",
  "כפר עבודה",
  "משמרת",
  "יעף",
  "חירות",
  "כפר יעבץ",
  "צור משה",
  "פרדסיה",
  "צורן",
  "שפיים",
  "מכון וינגייט",
  "געש",
  "ארסוף",
  "ארסוף קדם",
  "יקום",
  "חצר געש",
  "בני ציון",
  "חרוצים",
  "בצרה",
  "רשפון",
  "כפר סבא",
  "ירקונה",
  "כפר מלל",
  "תל אשר",
  "רמות השבים",
  "עדנים",
  "נווה ימין",
  "שדה ורבורג",
  "גן חיים",
  "גני עם",
  "צופית",
  "אלישמע",
  "הוד השרון",
  "שדי חמד",
  "רמת הדר",
  "בית ברל",
  "כפר ויתקין",
  "בית ינאי",
  "בית חרות",
  "גבעת שפירא",
  "מבואות ים",
  "שושנת העמקים",
  "חופית",
  "בת חן",
  "אביחיל",
  "מכמורת",
  "ביתן אהרון",
  "חבצלת השרון",
  "אבן יהודה",
  "כפר נטר",
  "אודים",
  "בית יהושע",
  "תל יצחק",
  "רעננה",
];

/** טיב טעם: 49 settlements, read 2026-08-02 from https://www.tivtaam.co.il/v2/retailers/1062/branches/937/areas?appId=4&deliveryTypeId=1&languageId=1. */
export const TIV_TAAM_ASHDOD: readonly string[] = [
  "אשדוד",
  "קבוצת יבנה",
  "עשרת",
  "כפר מרדכי",
  "גבעת וושינגטון",
  "בני דרום",
  "ניר גלים",
  "מישר",
  "כפר אביב",
  "משגב דב",
  "שדמה",
  "גן הדרום",
  "גן יבנה",
  "בצרון",
  "בית עזרא",
  "גבעתי",
  "שדה עוזיהו",
  "אמונים",
  "עזריקם",
  "קריית מלאכי",
  "כפר ורבורג",
  "שתולים",
  "באר טוביה",
  "עזר",
  "אורות",
  "תימורים",
  "כפר אחים",
  "קדרון",
  "בני עי\"ש",
  "חצב",
  "נווה מבטח",
  "גדרה",
  "ניר ישראל",
  "כפר סילבר",
  "ניצן",
  "ניצנים",
  "באר גנים",
  "אשקלון",
  "כוכב מיכאל",
  "שדה יואב",
  "נגבה",
  "נרניה",
  "שדרות",
  "ניר עם",
  "דורות",
  "יבנה",
  "מזכרת בתיה",
  "נס ציונה",
  "רחובות",
];

/** טיב טעם: 50 settlements, read 2026-08-02 from https://www.tivtaam.co.il/v2/retailers/1062/branches/1841/areas?appId=4&deliveryTypeId=1&languageId=1. */
export const TIV_TAAM_HAIFA: readonly string[] = [
  "חיפה",
  "קרית אתא",
  "קרית חיים",
  "קרית ים",
  "קרית מוצקין",
  "קרית ביאליק",
  "כפר ביאליק",
  "רמת יוחנן",
  "כפר המכבי",
  "אושה",
  "נשר",
  "טירת הכרמל",
  "יקנעם",
  "יקנעם עילית",
  "קרית טבעון",
  "שער העמקים",
  "בית שערים",
  "בית זיד",
  "יגור",
  "תמרת",
  "נופית",
  "רכסים",
  "רמת ישי",
  "כפר חסידים",
  "נהלל",
  "אלוני אבא",
  "נווה יער",
  "כפר יהושע",
  "שדה יעקב",
  "אלונים",
  "בית לחם הגלילית",
  "גבת",
  "רמת דוד",
  "נהריה",
  "עכו",
  "מסריק",
  "עברון",
  "בוסתן הגליל",
  "לוחמי הגטאות",
  "רגבה",
  "שבי ציון",
  "שמרת",
  "שורשים",
  "זכרון יעקב",
  "טבריה",
  "חדרה",
  "קיסריה",
  "אור עקיבא",
  "חריש",
  "קציר",
];

/** טיב טעם: 8 settlements, read 2026-08-02 from https://www.tivtaam.co.il/v2/retailers/1062/branches/939/areas?appId=4&deliveryTypeId=1&languageId=1. */
export const TIV_TAAM_BEER_SHEVA: readonly string[] = [
  "באר שבע",
  "שגב שלום",
  "מיתר",
  "כרמים",
  "עומר",
  "להבים",
  "אופקים",
  "נתיבות",
];

/**
 * Published zone labels, and the settlements each one actually reaches.
 *
 * WHY THIS EXISTS
 *
 * The header above claims a retailer's own spelling needs no normalising because
 * `canonicalizeCity` collapses the variants. That was wrong, and it was wrong in
 * the one direction that costs coverage. Retailers do not publish settlement
 * names; they publish SALES AREAS, and a sales area is named for the convenience
 * of the depot: "מרכז וצפון תל אביב (עד ארלוזורוב)", "רמלה לוד", "מזרח ירושלים",
 * "ק.אתא ביאליק". None of those is a place, so none of them ever matched, and a
 * rule that never matches reads as coverage in the table and behaves as none.
 *
 * The damage was concentrated exactly where it hurt most: Tel Aviv saw five
 * storefronts and not Rami Levy, Tiv Taam or Victory, all three of which publish
 * it; Jerusalem saw three and not Carrefour, Quik, Yeinot Bitan or Victory.
 *
 * Anything that is genuinely a single settlement is left alone: names the
 * canonical table has never heard of still match by identity when the shopper
 * types the same name, which is how ~450 small moshavim work.
 */
const ZONE_EXPANSIONS: Record<string, readonly string[]> = {
  // Tel Aviv, written six ways by four retailers, never as the city's own name.
  "מרכז וצפון תל אביב (עד ארלוזורוב)": ["תל אביב-יפו"],
  "תל אביב דרום/יפו": ["תל אביב-יפו"],
  "תל אביב צפון": ["תל אביב-יפו"],
  "תל אביב יפו מרכז דרום": ["תל אביב-יפו"],
  "תל אביב - רמת אביב": ["תל אביב-יפו"],
  "תל אביב - רמת החייל": ["תל אביב-יפו"],
  "תל אביב - אפקה": ["תל אביב-יפו"],
  "תל אביב - מרכז": ["תל אביב-יפו"],
  "תל אביב - דרום": ["תל אביב-יפו"],
  // רמת אביב is a Tel Aviv neighbourhood sharing a label with a real town.
  "רמת השרון, רמת אביב": ["רמת השרון", "תל אביב-יפו"],

  // Jerusalem, cut into sales areas by two retailers.
  "מזרח ירושלים": ["ירושלים"],
  "מערב ירושלים": ["ירושלים"],
  "צפון ירושלים": ["ירושלים"],
  "ירושלים 2": ["ירושלים"],
  "ירושלים צפון חדש": ["ירושלים"],
  "ירושלים צפון קצה למעלה": ["ירושלים"],

  // One city under a zone qualifier.
  "ראשון לציון מערב": ["ראשון לציון"],
  "ראשון לציון (מערב)": ["ראשון לציון"],
  "בני ברק עסקי": ["בני ברק"],
  "חיפה עיר תחתית": ["חיפה"],
  "רמת גן 1": ["רמת גן"],
  "אקים דימונה": ["דימונה"],
  "פארק התעשייה קיסריה": ["קיסריה"],
  "גן יבנה וסביבה": ["גן יבנה"],
  "שדרות הסביבה ועוטף": ["שדרות"],

  // Two or more cities sharing one delivery run.
  "רמלה לוד": ["רמלה", "לוד"],
  "נתיבות אופקים": ["נתיבות", "אופקים"],
  "רמת גן גבעתיים": ["רמת גן", "גבעתיים"],
  "כוכב יאיר אלישמע": ["כוכב יאיר", "אלישמע"],
  "אורנית שערי תקווה אלקנה": ["אורנית", "שערי תקווה", "אלקנה"],
  "גני תקווה וקרית אונו": ["גני תקווה", "קריית אונו"],
  // A valley, not a town. Claimed as its principal settlement only: naming the
  // whole valley would assert coverage of Yehud, Savyon and Or Yehuda that the
  // retailer's own label does not spell out, and over-claiming a delivery
  // promise is the one direction this file must not be wrong in.
  "בקעת אונו": ["קריית אונו"],

  // Krayot shorthand. קרית חיים is a Haifa quarter, not a town of its own.
  "ק.עקרון": ["קריית עקרון"],
  "ק.אתא ביאליק": ["קריית אתא", "קריית ביאליק"],
  "ק.מוצקין ים חיים": ["קריית מוצקין", "קריית ים", "חיפה"],
  "חיפה והקריות": [
    "חיפה",
    "קריית אתא",
    "קריית ביאליק",
    "קריית מוצקין",
    "קריית ים",
    "נשר",
  ],
};

/**
 * Labels that name a region rather than any settlement, kept out of the table on
 * the same rule the header states: a rule that can never match is worse than an
 * absent one. Listed rather than silently skipped so the count is auditable.
 */
const UNMATCHABLE_REGIONS: readonly string[] = ["דרום הר חברון"];

const ZONE_BY_KEY = new Map<string, readonly string[]>(
  Object.entries(ZONE_EXPANSIONS).map(([label, cities]) => [normalizeCityKey(label), cities]),
);
const DROPPED_BY_KEY = new Set(UNMATCHABLE_REGIONS.map((label) => normalizeCityKey(label)));

/**
 * One published delivery-area label into the settlement names it serves.
 *
 * Explicit table first, then a plain comma/slash split, because several lists
 * pack a whole delivery run into one cell ("חולון, בת ים, בית דגן, אזור"). The
 * split has to come second: "רמת השרון, רמת אביב" would otherwise yield the
 * neighbourhood רמת אביב, which matches nothing.
 */
export function expandDeliveryArea(published: string): string[] {
  const key = normalizeCityKey(published);
  const mapped = ZONE_BY_KEY.get(key);
  if (mapped) return [...mapped];
  if (DROPPED_BY_KEY.has(key)) return [];
  return published
    .split(/[,/]/)
    .map((part) => part.trim())
    .filter(Boolean);
}
